version: '2.1'

services:

  postgres:
    image: postgres
    container_name: prescription_db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./create-database-dev.sh:/docker-entrypoint-initdb.d/create-database-dev.sh
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      PGPASSWORD: pass